Instructions for building dnst
If I can believe the command output, there's a `dnst` missing in the description of building `dnst`:

```
$ cargo install --locked --bin dnst --git https://github.com/nlnetlabs/dnst
    Updating git repository `https://github.com/nlnetlabs/dnst`
error: multiple packages with binaries found: dnst, dnst-ldnsutils. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/nlnetlabs/dnst dnst`.
```

Hence this tiny PR.